apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prod-app
  namespace: argocd
spec:
  destination:
    namespace: prod
    server: https://kubernetes.default.svc
  project: webapp
  source:
    path: argo-rollouts/canary-strategy/prod
    repoURL: https://github.com/thiha1010/argo-labs.git
    targetRevision: release
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
