apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  labels:
    app: web
    tier: front
  name: web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  strategy:
    blueGreen:
      autoPromotionEnabled: true
      autoPromotionSeconds: 30
      activeService: web
      previewService: web-preview
  template:
    metadata:
      labels:
        app: web
        tier: front
    spec:
      containers:
      - image: quay.io/thiha0000/python-app:v2
        name: web
        imagePullPolicy: Always
        resources: 
          requests:
            cpu: "50m"
            memory: "64Mi"
          limits: 
            cpu: "250m"
            memory: "128Mi"
