apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
    tier: front
  name: web
spec:
  ports:
  - name: "80"
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: web
  type: ClusterIP
