---
apiVersion: v1
kind: Service
metadata:
  name: web-preview
  labels:
    role: web
spec:
  selector:
    app: web
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      nodePort: 30100
  type: NodePort
